services:
  mysql-db:
    image: mysql:9.0
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: catalogo_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306" 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge