spring.application.name=catalogo
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:rubrica_db}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}

# configurazioni per JPA
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.show-sql=true

# configurazioni del framework (impostazione su redirect)
server.forward-headers-strategy=framework